### ISSUE TITLE
BigDoors not working at all on 1.19.1

### ISSUE THREAD

**Issue by Chris6ix** [PimvanderLoos/AnimatedArchitecture#145]
Hey, I updated my server to 1.19.1 (from 1.18.2) and BigDoors just doesn't work at all anymore...
When I click on the "Toggle Door" Button in the menu, it just says `[BigDoors] Sliding Door DoorID "DoorName" is not available right now!` and nothing happens...sometimes it also throws this error:

`[BigDoors] Task #31454 for BigDoors vAlpha 0.1.8.39 (b1107) generated an exception
java.lang.NoSuchMethodError: 'double nl.pim16aap2.bigDoors.NMS.CustomEntityFallingBlock_V1_19_R1.dg()'
        at nl.pim16aap2.bigDoors.NMS.CustomEntityFallingBlock_V1_19_R1.<init>(CustomEntityFallingBlock_V1_19_R1.java:42) ~[BigDoors.jar:?]
        at nl.pim16aap2.bigDoors.NMS.FallingBlockFactory_V1_19_R1.fallingBlockFactory(FallingBlockFactory_V1_19_R1.java:20) ~[BigDoors.jar:?]
        at nl.pim16aap2.bigDoors.moveBlocks.SlidingMover.createAnimatedBlocks(SlidingMover.java:125) ~[BigDoors.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.1.jar:git-Paper-95]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.1.jar:git-Paper-95]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1491) ~[paper-1.19.1.jar:git-Paper-95]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.19.1.jar:git-Paper-95]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1415) ~[paper-1.19.1.jar:git-Paper-95]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1191) ~[paper-1.19.1.jar:git-Paper-95]        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.1.jar:git-Paper-95]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]`
        
There is no error or something on startup, so I don't know why it's not working...

I'm using Paper 1.19.1 #95 if that helps

**Comment by Chris6ix** [comment]
Never mind, I just noticed that there is a 1.19.1 dev build available 😅

**Comment by PimvanderLoos** [comment]
Yep, the dev-build has full support for 1.19.1. 
It'll be released on Spigot soon.
