### ISSUE TITLE
problem with the griefdefender

### ISSUE THREAD

**Issue by haroldrc** [PimvanderLoos/AnimatedArchitecture#161]
[11:36:55 WARN]: [BigDoors] Failed to initialize the "GriefDefender" (version "2.2.2") compatibility hook!
[11:36:55 WARN]: [BigDoors] Now resuming normal startup with the "GriefDefender" Compatibility Hook disabled!
[11:36:55 WARN]: [BigDoors] java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
        at BigDoors (3).jar//nl.pim16aap2.bigDoors.compatibility.ProtectionCompatManager.loadFromPluginName(ProtectionCompatManager.java:285)
        at BigDoors (3).jar//nl.pim16aap2.bigDoors.compatibility.ProtectionCompatManager.restart(ProtectionCompatManager.java:62)
        at BigDoors (3).jar//nl.pim16aap2.bigDoors.compatibility.ProtectionCompatManager.<init>(ProtectionCompatManager.java:50)
        at BigDoors (3).jar//nl.pim16aap2.bigDoors.BigDoors.onEnable(BigDoors.java:216)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542)
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:565)
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:479)
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:638)
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:424)
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:308)
        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1128)
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:307)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NoClassDefFoundError: com/griefdefender/GriefDefenderPlugin
        at BigDoors (3).jar//nl.pim16aap2.bigDoors.compatibility.GriefDefenderProtectionCompat.<init>(GriefDefenderProtectionCompat.java:21)
        ... 20 more
Caused by: java.lang.ClassNotFoundException: com.griefdefender.GriefDefenderPlugin
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:153)
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:105)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        ... 21 more

**Comment by PimvanderLoos** [comment]
Thanks for the report.

It looks like the hook will need to be updated. I'm currently on vacation, though, and do not have access to a computer. So I'm afraid this will have to wait until I'm back home in a few weeks.

**Comment by PimvanderLoos** [comment]
Closed in #169
