### ISSUE TITLE
1.19.3 compatibility

### ISSUE THREAD

**Issue by SlimeDog** [PimvanderLoos/AnimatedArchitecture#208]
Spigot 1.19.3-3616
BigDoors 0.1.8.40

On server start-up
```
[08:21:04] [Server thread/INFO]: [BigDoors] Enabling BigDoors vAlpha 0.1.8.40
[08:21:04] [Server thread/INFO]: [BigDoors] Power Block Types:
[08:21:04] [Server thread/INFO]: [BigDoors]  - GOLD_BLOCK
[08:21:04] [Server thread/INFO]: [BigDoors] Blacklisted materials:
[08:21:04] [Server thread/INFO]: [BigDoors]  - BEDROCK
[08:21:04] [Server thread/INFO]: [BigDoors]  - END_PORTAL
[08:21:04] [Server thread/INFO]: [BigDoors]  - END_PORTAL_FRAME
[08:21:04] [Server thread/INFO]: [BigDoors]  - NETHER_PORTAL
[08:21:04] [Server thread/INFO]: [BigDoors] Whitelisted materials:
[08:21:04] [Server thread/INFO]: [BigDoors]  - REDSTONE_BLOCK
[08:21:04] [Server thread/INFO]: [BigDoors] DestroyListed materials:
[08:21:04] [Server thread/INFO]: [BigDoors]  - LAVA
[08:21:04] [Server thread/INFO]: [BigDoors]  - WATER
[08:21:04] [Server thread/INFO]: [BigDoors]  - SNOW
[08:21:04] [Server thread/INFO]: [BigDoors]  - FERN
[08:21:04] [Server thread/INFO]: [BigDoors]  - GRASS
[08:21:04] [Server thread/INFO]: [BigDoors]  - TALL_GRASS
[08:21:04] [Server thread/INFO]: [BigDoors]  - SEAGRASS
[08:21:04] [Server thread/INFO]: [BigDoors]  - TALL_SEAGRASS
[08:21:04] [Server thread/WARN]: [BigDoors] ╔═══════════════════════════════════════════════════════╗
[08:21:04] [Server thread/ERROR]: [BigDoors] java.lang.Exception: Failed to generate NMS code! Please contact pim16aap2!
        at nl.pim16aap2.bigDoors.codegeneration.FallbackGeneratorManager.generateFallingBlockFactory(FallbackGeneratorManager.java:75)
        at nl.pim16aap2.bigDoors.codegeneration.FallbackGeneratorManager.getFallingBlockFactory(FallbackGeneratorManager.java:40)
        at nl.pim16aap2.bigDoors.BigDoors.compatibleMCVer(BigDoors.java:816)
        at nl.pim16aap2.bigDoors.BigDoors.onEnable(BigDoors.java:187)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:539)
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:453)
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:587)
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:412)
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:250)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:973)
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:301)
        at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: java.lang.ExceptionInInitializerError
        at nl.pim16aap2.bigDoors.codegeneration.FallbackGeneratorManager.getMappingsVersion(FallbackGeneratorManager.java:83)
        at nl.pim16aap2.bigDoors.codegeneration.FallbackGeneratorManager.generateFallingBlockFactory(FallbackGeneratorManager.java:55)
        ... 14 more
Caused by: java.lang.NullPointerException: Expected 1 method, but got 0 for input: [public static net.minecraft.world.level.block.state.IBlockData net.minecraft.nbt.GameProfileSerializer#[*](net.minecraft.nbt.NBTTagCompound)]. excluding superclasses, excluding interfaces
Found methods: []
        at nl.pim16aap2.bigDoors.reflection.ReflectionBackend.findMethod(ReflectionBackend.java:298)
        at nl.pim16aap2.bigDoors.reflection.MethodFinder$TypedMethodFinder.get(MethodFinder.java:218)
        at nl.pim16aap2.bigDoors.codegeneration.ReflectionRepository.<clinit>(ReflectionRepository.java:268)
        ... 16 more
```

**Comment by PimvanderLoos** [comment]
Thanks for the report.
I'll have some time to resolve the issue tomorrow.

**Comment by PimvanderLoos** [comment]
I've added support for 1.19.3, but XSeries hasn't been updated yet, so the new materials aren't supported yet and you'll get some messages on startup that the plugin is unable to match the materials. The plugin defaults to blacklisting any unknown materials, so until XSeries is updated, the new materials cannot be used in the doors. Other than that, everything should work now.

I have published dev-build 1115 [here](https://github.com/PimvanderLoos/BigDoors). A full release will follow once XSeries has been updated.

**Comment by SlimeDog** [comment]
Build 1115 seems to work fine on Spigot 1.19.2 and Spigot 1.19.3, with my limited door set. Thanks.

**Comment by SlimeDog** [comment]
You might want to consider moving away from [XSeries](https://github.com/CryptoMorin/XSeries), although you're not the only one. More than a week after Spigot 1.19.3 release, it hasn't been updated.

**Comment by PimvanderLoos** [comment]
Yeah, it usually takes a little while for XSeries to be updated. It is generally a useful library though, so I'd rather not move away from it. I'll give them a few more days to update it and if it's not available by then I'll just add the missing materials myself.

All new materials that could potentially be used by BigDoors are part of the experimental stuff anyway, so it's not really a big deal that they aren't supported yet.

**Comment by SlimeDog** [comment]
Agreed. I'm not concerned about the experimental materials. I'm concerned for the future that XSeries, like so many other resources have done, will fall by the wayside. It is open source, so I guess someone else could take it on at that point.

**Comment by PimvanderLoos** [comment]
It would not be such a big deal if XSeries wouldn't get updated anymore. I only use the XMaterial part of it, which should be easy enough to update, so I can always just fork it and do that myself. It would not be much more than a slight annoyance for me. Though I think that it'd be more of a headache for other users, so I'm sure someone would pick it up.

**Comment by PimvanderLoos** [comment]
I got tired of waiting for XSeries to get updated, so I went ahead and forked it and added support for 1.19.3 to XMaterial.

I'll publish the update on Spigot sometime ~today~ tomorrow. I've published a new dev-build for now.

**Comment by SlimeDog** [comment]
Confirmed fixed with BigDoors 0.1.8.41-b1116. Thanks.

**Comment by SlimeDog** [comment]
Note that XSeries just updated to support 1.19.3.

**Comment by PimvanderLoos** [comment]
Yeah, I saw. I was unable to release it on Spigot yet, so just going to go ahead and use the official XMaterial again and then publish it.

**Comment by SlimeDog** [comment]
Sounds good. I will test the dev build when available.

**Comment by PimvanderLoos** [comment]
Looking at the diff between my XMaterial update and the official one, there were no impactful differences (only a version bump in the documentation and apparently I struggle with alphabetical sorting), so I went ahead and published the full release. Thanks for the offer to test it, though, and of course for the testing of the previous builds as well!

**Comment by SlimeDog** [comment]
great, thanks.
